<a href="https://colab.research.google.com/github/SuleymanToklu/AI/blob/main/Hafta1_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Isparta University of Applied Sciences Artificial Intelligent Systems - Sinan Uğuz Texts

# NUMPY Module

**What is NumPy?**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, derived objects (such as masked arrays and matrices), and a variety of routines for fast operations on arrays (mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more).

At the core of the NumPy package is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, and many operations are performed in compiled code for performance. There are several important differences between NumPy arrays and standard Python sequences (like lists):

Fixed size: A NumPy array has a fixed size at creation. A Python list can grow dynamically. Changing the size of an ndarray will create a new array and delete the original.

Same data type: The elements of a NumPy array must all be of the same data type, and thus will be the same size in memory. The exception is that arrays of Python (and NumPy) objects can be maintained, in which case the elements can be of different sizes.

Advanced operations: NumPy arrays facilitate advanced mathematical and other types of operations on large amounts of data. These operations are often more efficient and require less code than doing similar operations with Python’s built-in sequences.

An increasing number of scientific and mathematical Python-based packages are using NumPy arrays. Although these packages will often accept Python sequences as input, they will convert them to NumPy arrays prior to processing, and will often output NumPy arrays.

In short, to use much of the scientific/mathematical Python-based software available today, and to do so efficiently, it is not sufficient to just know how to use Python’s built-in sequences; you also need to know how to use NumPy arrays.

**Source of NumPy's speed:**

Loops and heavy operations are performed at the C level instead of Python (vectorization).

Flexible and efficient handling of arrays of different dimensions (broadcasting).

NumPy's array class is called **ndarray**. This class is also simply called array. However, there is an important point to note:

👉 numpy.array is not the same thing as the array.array class in Python's standard library.

numpy.array (ndarray): Supports multidimensional arrays, offers mathematical operations, broadcasting, vectorization, and many advanced functionalities.

array.array (Standard Python Library): Supports only one-dimensional arrays and its functionality is quite limited.

In summary, NumPy's ndarray class is a much more powerful and flexible structure developed for use in scientific and numerical computations.

In [36]:
#List 2.1
import numpy as np

the import command adds a library

In [37]:
"""
 We have a single example here. This measurement represents temperature, humidity, wind speed, and pressure values from a weather station.
 Let's store it in a 1-dimensional array (vector).
"""
#List 2.2
veri=np.array([5.7,2.6,3.5,1.0])
print(veri)

[5.7 2.6 3.5 1. ]


In [38]:
"""
2-dimensional (single-row matrix)
A single example but a 2-dimensional table (1 row, 3 columns)
"""
#List 2.3
veri2=np.array([[2,5,7]])
print(veri2)

[[2 5 7]]


In [39]:
#List 2.4
print(np.array([[2,5,7], [3,6,8]]))

[[2 5 7]
 [3 6 8]]


In [40]:
#List 2.5
print(np.zeros(3))

[0. 0. 0.]


In [41]:
#List 2.6
print(np.zeros((4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
#List 2.7
print(np.zeros((2,4,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [43]:
#List 2.8
print(np.ones(4))

[1. 1. 1. 1.]


In [44]:
#List 2.9
print(np.full((2,2),"Python"))

[['Python' 'Python']
 ['Python' 'Python']]


In [45]:
#List 2.10
print(np.arange(0, 1, 0.2))

[0.  0.2 0.4 0.6 0.8]


In [46]:
#List 2.11
print(np.linspace(0.0, 1.0, num=5))
print(np.linspace(0.0, 1.0, num=5, endpoint=False))

[0.   0.25 0.5  0.75 1.  ]
[0.  0.2 0.4 0.6 0.8]


In [78]:
# Example
print(np.linspace(0, 100, num=5, retstep=True))

(array([  0.,  25.,  50.,  75., 100.]), np.float64(25.0))


In [47]:
#List 2.12
print(np.random.rand(2,2))
print(np.random.randn(2,2))

[[0.58993868 0.1288768 ]
 [0.27306348 0.22513666]]
[[-0.2617269  -0.49124083]
 [ 2.21433949 -1.25018116]]


In [84]:
#List 2.13
print(np.random.randint(1,50, size=(2, 3)))

[[30 30 10]
 [40 15 40]]


In [49]:
#List 2.14
dizi = np.arange(2.0, 9.0)
print(dizi.dtype,dizi)

float64 [2. 3. 4. 5. 6. 7. 8.]


In [50]:
#List 2.15
#.itemsize gives the amount of memory in bytes occupied by each element.
dizi = np.arange(1, 3, dtype=np.int64)
print(dizi.itemsize)

8


In [51]:
#List 2.16
dizi=np.arange(16)
print(dizi)
print("Number of Dimensions:", dizi.ndim)
dizi.shape=(4,4)
print(dizi)
print("Number of Dimensions:", dizi.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Number of Dimensions: 1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Number of Dimensions: 2


In [52]:
#List 2.17
#.ravel() flattens the array into a 1-dimensional array.
#By default, it follows the memory layout (C-order: row by row).
dizi=np.array([[2,5,7], [3,6,8]])
print(dizi)
x=dizi.ravel()
print(x)

[[2 5 7]
 [3 6 8]]
[2 5 7 3 6 8]


In [86]:
array_100 = np.arange(101)
print("Original array:", array_100)

split_array = np.split(array_100, [50,60])
print("Array split at index 50:", split_array)

Original array: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
Array split at index 50: [array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]), array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]), array([ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
        73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
        86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
        99, 100])]


In [53]:
#List 2.18
dizi1 = np.array([4, 6, 8, 9])
dizi2 = np.array([2, 4, 3, 5])
print("Sum  =", dizi1 + dizi2)
print("Difference  =", dizi1 - dizi2)
print("Multiplication  =", dizi1 * dizi2)
print("Division (float)  =", dizi1 / dizi2)
print("Division (integer)  =", dizi1 // dizi2)
print("Remainder  =", dizi1 % dizi2)
print("Power =", dizi1 ** dizi2)

Sum  = [ 6 10 11 14]
Difference  = [2 2 5 4]
Multiplication  = [ 8 24 24 45]
Division (float)  = [2.         1.5        2.66666667 1.8       ]
Division (integer)  = [2 1 2 1]
Remainder  = [0 2 2 4]
Power = [   16  1296   512 59049]


In [54]:
#List 2.19
dizi = np.array([[1, 2.5, 6], [8, 20, 11]])
for i in (dizi.min, dizi.max, dizi.sum, dizi.prod, dizi.std, dizi.var):
    print(i.__name__, "=", i())

min = 1.0
max = 20.0
sum = 48.5
prod = 26400.0
std = 6.274396828027022
var = 39.36805555555556


In [55]:
#List 2.20
#Takes the ceiling value of the number -> rounded up after the decimal point
#Checks for "Not a Number (NaN)" values.
dizi = np.array([[1, 2.5, 6], [8, 20, 11]])
for i in (np.abs, np.sqrt, np.ceil, np.isnan):
    print("\n", i.__name__)
    print(i(dizi))


 absolute
[[ 1.   2.5  6. ]
 [ 8.  20.  11. ]]

 sqrt
[[1.         1.58113883 2.44948974]
 [2.82842712 4.47213595 3.31662479]]

 ceil
[[ 1.  3.  6.]
 [ 8. 20. 11.]]

 isnan
[[False False False]
 [False False False]]


In [56]:
#List 2.21
dizi=np.array([5,12,4,-2,15,6,8,0])

In [57]:
#List 2.22
print(dizi[4])
print(dizi[1:5])

15
[12  4 -2 15]


In [58]:
#List 2.23
print(dizi[3:-1])

[-2 15  6  8]


In [59]:
#List 2.24
print(dizi[:4])

[ 5 12  4 -2]


In [60]:
#List 2.25
print(dizi[1::2])

[12 -2  6  0]


In [61]:
#List 2.26
print(dizi[::-1])

[ 0  8  6 15 -2  4 12  5]


In [62]:
#List 2.27
dizi[2:4]=11
print(dizi)

[ 5 12 11 11 15  6  8  0]


In [63]:
#List 2.28
dizi=np.array([5,12,4,-2,15,6,8,0])
print(dizi)
yeniDizi=dizi[2:4]
print(yeniDizi)
dizi[2]=200
print(yeniDizi)

[ 5 12  4 -2 15  6  8  0]
[ 4 -2]
[200  -2]


In [64]:
#List 2.29
dizi=np.array([5,12,4,-2,15,6,8,0])
print(dizi)
yeniDizi=dizi[2:4].copy()
print(yeniDizi)
dizi[2]=200
print(yeniDizi)

[ 5 12  4 -2 15  6  8  0]
[ 4 -2]
[ 4 -2]


In [65]:
#List 2.30
dizi=np.arange(12)
dizi.shape=(3,4)
print(dizi)
print(dizi[2,3])
print(dizi[0,:])
print(dizi[:,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
11
[0 1 2 3]
[ 2  6 10]


In [66]:
#List 2.31
print(dizi[:,(0,2)])
print(dizi[(0,1),1:3])

[[ 0  2]
 [ 4  6]
 [ 8 10]]
[[1 2]
 [5 6]]


In [67]:
#List 2.32
dizi=np.arange(12)
dizi.shape=(3,2,2)
print(dizi)
print(dizi[1,1,0])
print(dizi[1,:,0])

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
6
[4 6]


In [68]:
#List 2.33
dizi1 = np.full((2,4), 0.0)
dizi2 = np.full((3,4), 1.0)
dizi3 = np.full((4,4), 2.0)
print(dizi1);print(dizi2);print(dizi3)
dizi4 = np.concatenate((dizi1, dizi2, dizi3), axis=0)
print(dizi4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [69]:
#List 2.34
dizi1 = np.full((2,4), 0.0)
dizi2 = np.full((2,4), 1.0)
print(dizi1);print(dizi2)
dizi3 = np.concatenate((dizi1, dizi2), axis=1)
print(dizi3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


In [70]:
#List 2.35
dizi1= np.arange(12.0)
print(np.split(dizi1,4))

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.]), array([ 9., 10., 11.])]


In [71]:
# Example of np.array_split (List 2.36)
dizi1 = np.arange(12.0)
print("Original array:", dizi1)
print("Splitting into 5 sections using np.array_split:")
print(np.array_split(dizi1, 5))

dizi2 = np.arange(10.0).reshape(2, 5)
print("\nOriginal 2D array:\n", dizi2)
print("Splitting into 3 sections along axis 1 using np.array_split:")
print(np.array_split(dizi2, 3, axis=1))

Original array: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
Splitting into 5 sections using np.array_split:
[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.]), array([8., 9.]), array([10., 11.])]

Original 2D array:
 [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
Splitting into 3 sections along axis 1 using np.array_split:
[array([[0., 1.],
       [5., 6.]]), array([[2., 3.],
       [7., 8.]]), array([[4.],
       [9.]])]


In [72]:
# More NumPy operations

# Reshaping arrays
dizi = np.arange(12).reshape(3, 4)
print("\nOriginal array:\n", dizi)
print("\nReshaped to (4, 3):\n", dizi.reshape(4, 3))

# Transposing arrays
print("\nTransposed array:\n", dizi.T)

# Stacking arrays
dizi1 = np.array([1, 2, 3])
dizi2 = np.array([4, 5, 6])
print("\nStacking arrays vertically (vstack):\n", np.vstack((dizi1, dizi2)))
print("\nStacking arrays horizontally (hstack):\n", np.hstack((dizi1, dizi2)))

# Broadcasting (adding a scalar to an array)
print("\nArray + scalar (5):\n", dizi + 5)

# Universal functions (ufuncs)
print("\nApplying np.sin to the array:\n", np.sin(dizi))

# Boolean indexing
print("\nElements greater than 5:\n", dizi[dizi > 5])

# Sorting
dizi = np.array([9, 3, 7, 1, 5, 2, 8, 4, 6])
print("\nOriginal array for sorting:", dizi)
print("\nSorted array:", np.sort(dizi))

# Aggregations (mean, median, etc.)
dizi = np.arange(12).reshape(3, 4)
print("\nOriginal array for aggregations:\n", dizi)
print("\nMean of the array:", np.mean(dizi))
print("\nMedian of the array:", np.median(dizi))
print("\nSum of elements along axis 0:", np.sum(dizi, axis=0))


Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to (4, 3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Stacking arrays vertically (vstack):
 [[1 2 3]
 [4 5 6]]

Stacking arrays horizontally (hstack):
 [1 2 3 4 5 6]

Array + scalar (5):
 [[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Applying np.sin to the array:
 [[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]

Elements greater than 5:
 [ 6  7  8  9 10 11]

Original array for sorting: [9 3 7 1 5 2 8 4 6]

Sorted array: [1 2 3 4 5 6 7 8 9]

Original array for aggregations:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Mean of the array: 5.5

Median of the array: 5.5

Sum of elements along axis 0: [12 15 18 21]
